# Generated by Django 4.2.2 on 2023-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=24)),
                ('year', models.IntegerField()),
                ('body_type', models.CharField(max_length=18)),
                ('seats', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
