# Generated by Django 4.2.2 on 2023-06-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_auto_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
